### ISSUE TITLE
Installation fails with an error

### ISSUE THREAD

**Issue by nunomira** [mpociot/laravel-test-factory-helper#1]
I have tried to install this package (on a fresh Laravel 5.2.27 installation) using _composer require_, but I get an error:
```
[Symfony\Component\Debug\Exception\FatalErrorException]
Class 'Mpociot\LaravelTestFactoryHelper\TestFactoryHelperServiceProvider' not found

Script php artisan optimize handling the post-update-cmd event returned with an error

Installation failed, reverting ./composer.json to its original content.

[RuntimeException]
Error Output:
```
the same happens when I run
`php artisan test-factory-helper:generate`

```
[Symfony\Component\Debug\Exception\FatalErrorException]

Class 'Mpociot\LaravelTestFactoryHelper\TestFactoryHelperServiceProvider' not found
```

**Comment by ionut-tanasa** [comment]
Try adding the service provider to app.php after installing the package.

**Comment by nunomira** [comment]
Hi, thanks.
I have added it:
`Mpociot\LaravelTestFactoryHelper\TestFactoryHelperServiceProvider::class,`

If I remove it, a different error is received:

```
[Symfony\Component\Console\Exception\CommandNotFoundException]

There are no commands defined in the "test-factory-helper" namespace.
```

**Comment by ionut-tanasa** [comment]
Of course the command won't work if you don't include the provider. 

Try this if you haven't already. 

Comment out or remove the provider from the app.php file
Composer update to pull down the package
Add the provider to app.php
Run composer dumpautoload -o just to be sure.

**Comment by nunomira** [comment]
No luck...
All the same.
I have even tried to do it from within homestead (homestead ssh, just to eliminate a windows problem) but the result is the same.

**Comment by ionut-tanasa** [comment]
Maybe you still have it somewhere else? 

I can confirm the package works great. I installed it on a few projects already. 


Try deleting manually the vendor folder and the composer.lock file and run a clean composer install.

**Comment by nunomira** [comment]
Don't know what happened to my last answer... but it wasn't submitted after all.

I tried that as well - thanks - no luck.
I even tried a new project - all the same.
But it seems like I'm the only one having this problem. Really frustrating!
I was really curious about this :)

**Comment by nunomira** [comment]
This is surreal...
I tried it on an existing project and it installed without issues!

**Comment by nunomira** [comment]
And now on another new project it installed as well.

**Comment by LukasMa** [comment]
@nunomira I'm having the exact same issue! Installed it yesterday at home and it worked. Pushed my changes, pulled them today on another machine: Wont work. Got back home, and somehoe can't get it to work.

**Comment by mpociot** [comment]
@LukasMa have you tried running `composer update` after pulling the changes?
These issues are not related to the package itself, but seem to be an installation issue.

**Comment by ghkdev** [comment]
Autoloader is trying to load this file
```
...../vendor/mpociot/laravel-test-factory-helper/src/Mpociot/LaravelTestFactoryHelper/TestFactoryHelperServiceProvider.php
```
but the real location is
```
.../vendor/mpociot/laravel-test-factory-helper/src/TestFactoryHelperServiceProvider.php
```

**Comment by mpociot** [comment]
Fixed with the latest release
