### ISSUE TITLE
Not Support in laravel 5.4

### ISSUE THREAD

**Issue by trixanapp** [mpociot/laravel-test-factory-helper#14]
Problem - mpociot/laravel-test-factory-helper 0.3.1 requires illuminate/support 5.0.x|5.1.x|5.2.x|5.3.x
 and - mpociot/laravel-test-factory-helper 0.3.1 requires illuminate/filesystem 5.0.x|5.1.x|5.2.x|5.3.x
don't install laravel/framework v5.4.0

**Comment by thinkstylestudio** [comment]
@trixanapp were you able to get this up and running? Why close the issue?

**Comment by trixanapp** [comment]
Not working. 
Wait Laravel Collective 5.4.
Patience is appreciated.
sorry my bad english.
Thanks.

**Comment by thinkstylestudio** [comment]
Right that makes sense and no worries.

**Comment by trixanapp** [comment]
Fixed it.
