### ISSUE TITLE
Doesn't find Models

### ISSUE THREAD

**Issue by wahidsherief** [mpociot/laravel-test-factory-helper#5]
This package doesn't find models in namespace "App". shows : PHP Fatal error:  Class 'Bear' not found in /opt/lampp/htdocs/blog/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php on line 790

Why it searches in vendor folder ??

**Comment by mpociot** [comment]
Sorry, I'm unable to reproduce this issue.

Can you give me some more information? Like the namespace and class header of the file that cannot be found?
