### ISSUE TITLE
Laravel 4.2

### ISSUE THREAD

**Issue by Alexwijn** [mpociot/laravel-test-factory-helper#6]
Any change for a laravel 4.2 version? A lot of projects are still using it and are still under active development.

**Comment by mpociot** [comment]
Laravel 4 has no official `factory` helper.

It could work with using the [laracasts/TestDummy](https://github.com/laracasts/TestDummy) package

**Comment by Alexwijn** [comment]
Yeah, that's what I'm using also.

**Comment by jrmadsen67** [comment]
seems like an adequate workaround, and 4.2 is beyond what will be supported here.

#close
