### ISSUE TITLE
Not working on laravel 5.3

### ISSUE THREAD

**Issue by dieg0** [mpociot/laravel-test-factory-helper#9]
Problem 1
    - Installation request for mpociot/laravel-test-factory-helper ^0.2.1 -> satisfiable by mpociot/laravel-test-factory-helper[0.2.1].
    - Conclusion: remove laravel/framework 5.3.x-dev
    - mpociot/laravel-test-factory-helper 0.2.1 requires illuminate/filesystem 5.0.x|5.1.x|5.2.x -> satisfiable by laravel/framework[5.2.x-dev], illuminate/filesystem[5.0.x-dev, 5.1.x-dev, 5.2.x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.28, v5.1.30, v5.1.31, v5.1.6, v5.1.8, v5.2.0, v5.2.19, v5.2.21, v5.2.24, v5.2.25, v5.2.26, v5.2.27, v5.2.28, v5.2.31, v5.2.32, v5.2.37, v5.2.6, v5.2.7].
    - Can only install one of: laravel/framework[5.3.x-dev, 5.2.x-dev].
    - don't install illuminate/filesystem 5.2.x-dev|don't install laravel/framework 5.3.x-dev

**Comment by brnmonteiro** [comment]
any prevision for test-factory for 5.3 @mpociot ?

**Comment by mpociot** [comment]
Please use version 0.3.0 for Laravel 5.3

**Comment by brnmonteiro** [comment]
Problem 1
    - Installation request for mpociot/laravel-test-factory-helper 0.3.0 -> satisfiable by mpociot/laravel-test-factory-helper[0.3.0].
    - mpociot/laravel-test-factory-helper 0.3.0 requires symfony/class-loader dev-master -> satisfiable by symfony/class-loader[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by mpociot** [comment]
Sorry for that, just released 0.3.1 which uses a stable version of symfony/class-loader
